#print(3+3+"python")
#print("7"-2)
#print("charan"-"tech")
print("charan\n\ttech")
print("charan\n\t'tech")
#print ("**charan tech**)
print("\n---python---")
print("\t\tneeraj\tsale")
print("\t\t========")