print("neeraj"+"sale")
print(4+2)
print(12-6)
print("12"+"5")
print(10/2)
print("sathya","tech")
print("core","-","python")
print("\n","charan","-","tech")
#print("python"+3)
#print(3+3+"python")
#print("7"-2)
#print("charan"-"tech")
print("charan\n\ttech")
print("charan\n\t'tech")
#print ("**charan tech**)
print("\n---python---")
print("\t\tneeraj\tsale")
print("\t\t========")